// <auto-generated />
namespace Qubiz.QuizEngine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-beta1-30916")]
    public sealed partial class _113_Add_FeatureFlag_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_113_Add_FeatureFlag_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201509020904036_113_Add_FeatureFlag_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
